=== DabSkrys/Protectora.github.io/ProtectoraWebAnimales/xml/fitxaMascotas.dtd
<!ELEMENT veterinario (mascota+)>

<!ELEMENT mascota (chip, nombre, fechaNacimiento, pedigree, peso,
 color, foto, propietario?, vacunas, visitas)>
<!ATTLIST mascota idMascota ID #REQUIRED sexo (macho | hembra) #REQUIRED tipoPelo (corto | largo | rizado) #REQUIRED>

<!ELEMENT chip (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fechaNacimiento (#PCDATA)>
<!ELEMENT pedigree (#PCDATA)>
<!ELEMENT peso (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT foto (#PCDATA)>

<!ELEMENT propietario (nombre, apellido, direccion, email, telefono)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>

<!ELEMENT vacunas (vacuna*)>
<!ELEMENT vacuna (nombre, fechaAdministracion?, fechaProxima?)>
<!ATTLIST vacuna laboratorio CDATA #IMPLIED>

<!ELEMENT fechaAdministracion (#PCDATA)>
<!ELEMENT fechaProxima (#PCDATA)>

<!ELEMENT visitas (visita+)>
<!ELEMENT visita (fecha, motivo, diagnostico, tratamiento, alta)>
<!ATTLIST visita idVisita ID #REQUIRED>

<!ELEMENT fecha (#PCDATA)>
<!ELEMENT motivo (#PCDATA)>
<!ELEMENT diagnostico (#PCDATA)>
<!ELEMENT tratamiento (#PCDATA)>
<!ELEMENT alta (#PCDATA)>

=== DabSkrys/Protectora.github.io/ProtectoraWebAnimales/xml/fitxa de la mascota.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="fitxa_mascotes_transformado.xsl"?>
<!DOCTYPE veterinario SYSTEM "fitxaMascotas.dtd">

<veterinario>
  <mascota idMascota="M001" sexo="macho" tipoPelo="corto">
    <chip>123456789567164</chip>
    <nombre>Rocky</nombre>
    <fechaNacimiento>12-05-2018</fechaNacimiento>
    <pedigree>true</pedigree>
    <peso>25.4</peso>
    <color>blanco</color>
    <foto>../imagenes/rocky.jpg</foto>
    <propietario>
      <nombre>Laura</nombre>
      <apellido>Gómez</apellido>
      <direccion>Calle Mayor 12, Madrid</direccion>
      <email>lauragomez@gmail.com</email>
      <telefono>665487539</telefono>
    </propietario>
    <vacunas>
      <vacuna laboratorio="Elanco">
        <nombre>Rabia</nombre>
        <fechaAdministracion>10-06-2023</fechaAdministracion>
        <fechaProxima>10-06-2024</fechaProxima>
      </vacuna>
    </vacunas>
    <visitas>
      <visita idVisita="V001">
        <fecha>15-09-2023</fecha>
        <motivo>Revisión anual</motivo>
        <diagnostico>Salud óptima</diagnostico>
        <tratamiento>Ninguno</tratamiento>
        <alta>true</alta>
      </visita>
    </visitas>  
  </mascota>

  <mascota idMascota="M002" sexo="hembra" tipoPelo="largo">
    <chip>945675184379157</chip>
    <nombre>Nina</nombre>
    <fechaNacimiento>07-07-2021</fechaNacimiento>
    <pedigree>false</pedigree>
    <peso>11.8</peso>
    <color>marron</color>
    <foto>../imagenes/nina.jpg</foto>
    <propietario>
      <nombre>James</nombre>
      <apellido>Polo</apellido>
      <direccion>Plaza Luna 8, Valencia</direccion>
      <email>jamespolo@gmail.com</email>
      <telefono>669784311</telefono>
    </propietario>
    <vacunas>
      <vacuna laboratorio="Zoetis">
        <nombre>Leptospirosis</nombre>
        <fechaAdministracion>24-11-2022</fechaAdministracion>
        <fechaProxima>24-11-2023</fechaProxima>
      </vacuna>
    </vacunas>
    <visitas>
      <visita idVisita="V002">
        <fecha>17-02-2023</fecha>
        <motivo>Vómitos</motivo>
        <diagnostico>Gastroenteritis canina</diagnostico>
        <tratamiento>Antibióticos</tratamiento>
        <alta>false</alta>
      </visita>
    </visitas>
  </mascota>

  <mascota idMascota="M003" sexo="macho" tipoPelo="rizado">
    <chip>461279427942491</chip>
    <nombre>Zeus</nombre>
    <fechaNacimiento>29-03-2015</fechaNacimiento>
    <pedigree>true</pedigree>
    <peso>18.2</peso>
    <color>negro</color>
    <foto>../imagenes/zeus.jpg</foto>
    <propietario>
      <nombre>Max</nombre>
      <apellido>Martinez</apellido>
      <direccion>Avenida del Sol 45, Barcelona</direccion>
      <email>maxmartinez@gmail.com</email>
      <telefono>664875195</telefono>
    </propietario>
    <vacunas>
      <vacuna laboratorio="Merck MSD salud animal">
        <nombre>Moquillo</nombre>
        <fechaAdministracion>12-03-2021</fechaAdministracion>
        <fechaProxima>12-03-2022</fechaProxima>
      </vacuna>
    </vacunas>
    <visitas>
      <visita idVisita="V003">
        <fecha>30-07-2021</fecha>
        <motivo>Herida en la pata</motivo>
        <diagnostico>Corte en la superficie</diagnostico>
        <tratamiento>Desinfección y vendaje</tratamiento>
        <alta>true</alta>
      </visita>
    </visitas>
  </mascota>
</veterinario>
